#162725218 Users should be able to signup
andela/Ah-frontend-xmen pull request #14
Opened 2019-02-16 10:44 UTC by armstrongsouljah

##### What does this Pr do?
- Adds an implementation to enable users to create new accounts on the authors' heaven platform.

##### Description of the task to be implemented.
- Create  a signup form to allow users to enter the details for their new accounts
- Create a component to handle the signup process by sending user information to the backend API.
- Connect the component to the global store.
- When users enter incorrect details, they should be presented with descriptive validation errors.

#### How can this be manually tested?
- Fetch this branch to your local machine by running `git fetch origin ft-users-should-signup-162725218` in your terminal.
- Checkout to this branch by running ` git checkout ft-users-should-signup-162725218` in your terminal.
- Start the development server by running `yarn start` in your terminal.
- Navigate to the signup route by clicking on the `Register` link in the browser.
- Enter your details into the form and click the signup button.
- On success, you should receive an email inviting you to verify your email.

#### What are the related pivotal stories?
[162725218](https://www.pivotaltracker.com/story/show/162725218)

2019-02-18 07:09 UTC, MuhweziDeo commented
@armstrongsouljah  everything looks good, redux actions are dispatched and work fine, but maybe you would want to save the access token created on signup in local storage. such as the users can access the platform

2019-02-20 13:01 UTC, RrNn requested changes

2019-02-20 13:01 UTC, RrNn commented on src/actions/__tests__/signupAction.test.js
> +describe('async actions', () => {
You need to update the description here. What are `async actions`?

2019-02-20 13:01 UTC, RrNn commented on src/actions/__tests__/signupAction.test.js
> +const postUrl = 'https://ah-backend-xmen.herokuapp.com/api/users/';
Remember to get this URI from the environment later.

2019-02-20 13:01 UTC, RrNn commented on src/actions/__tests__/signupAction.test.js
> +  it('creates REGISTER_FAILURE when registerUser is done', () => {
Perhaps it **dispatches**, not **creates**

2019-02-20 13:01 UTC, RrNn commented on src/components/Header.js
> +/* eslint-disable import/no-named-as-default */
Why are you disabling our ESLint?

2019-02-20 13:01 UTC, RrNn commented on src/views/__tests__/RegisterView.test.js
> +    // const handleUsernameChanged = jest.fn();
Remove the commented out code.

2019-02-20 13:01 UTC, RrNn commented on src/routes/index.js
> +// import RegisterView from '../views/RegisterView';
Remove commented out code.

2019-02-20 13:01 UTC, RrNn commented on src/views/RegisterView.js
> +    // const { signupState } = this.props;
Remove this line

2019-02-20 13:01 UTC, RrNn commented on src/views/RegisterView.js
> +    // eslint-disable-next-line no-shadow
Remove this line

2019-02-20 13:01 UTC, RrNn commented on src/views/__tests__/RegisterView.test.js
> +// import Adapter from 'enzyme-adapter-react-16';
Remove this line

2019-02-20 13:21 UTC, armstrongsouljah commented on src/actions/__tests__/signupAction.test.js
> +describe('async actions', () => {
Thank you @RrNn for pointing this out. Let me make the test more descriptive.

2019-02-20 13:24 UTC, armstrongsouljah commented on src/components/Header.js
> +/* eslint-disable import/no-named-as-default */
I forgot about these lines. But am looking into them.

2019-02-21 14:13 UTC, MuhweziDeo submitted a review, later dismissed
LGTM @armstrongsouljah  everything seems to be running fine

2019-02-21 17:45 UTC, MuhweziDeo reviewed
Everything checks out

2019-02-22 06:07 UTC, calvinpete submitted a review, later dismissed
LGTM

2019-02-22 06:32 UTC, MuhweziDeo submitted a review, later dismissed
@armstrongsouljah  Good work on this, everything checks out

2019-02-22 15:08 UTC, merged