#162725235 Users should bookmark articles
andela/Ah-frontend-xmen pull request #32
Opened 2019-02-28 14:27 UTC by armstrongsouljah

#### What does this PR do?
- Enables users to bookmark articles for reading later

#### Description the task to be implemented
- Users should be able to bookmark articles for reading later via a bookmark tab, button or link
- Implement bookmarking functionality
- Write tests for bookmarking functionality
- Render a list of bookmarked articles in the user's profile

#### How can this be manually tested?
- Fetch this branch by running `git fetch origin ft-bookmark-articles-162725235`
- Checkout to this branch by running ` git checkout ft-bookmark-articles-162725235`
- Install dependencies by running `yarn`
- Start the local server by running `yarn start`
- Log in with either `social auth` or the `login form`
- Bookmark any article by clicking on the bookmark icon
- View your bookmarks by visiting your profile and checking the bookmarked articles tab.

#### Screenshots if necessary.
<img width="1433" alt="screenshot 2019-02-28 at 17 25 32" src="https://user-images.githubusercontent.com/18280598/53573218-05c18f00-3b7e-11e9-9ffb-1183c4ce44ea.png">

#### What are the related pivotal stories?
[#162725235](https://www.pivotaltracker.com/story/show/162725235)

2019-03-04 07:53 UTC, RrNn commented
@armstrongsouljah could you give the `bookmark` icon a better cursor on hover.

2019-03-04 07:54 UTC, armstrongsouljah commented
> @armstrongsouljah could you give the `bookmark` icon a better cursor on hover.

okay.

2019-03-04 08:31 UTC, armstrongsouljah commented
@RrNn I have added the hover style. All is good to go.

2019-03-04 09:47 UTC, MuhweziDeo submitted a review, later dismissed
LGTM

2019-03-04 09:53 UTC, calvinpete reviewed
@armstrongsouljah Please refactor the command line for installing dependencies to `yarn install`.

2019-03-04 09:54 UTC, kdaglas submitted a review, later dismissed
i have tested it, i like the tooltips implementation

2019-03-04 10:42 UTC, MuhweziDeo commented
Please @armstrongsouljah  check a bug u have when I bookmark an article and visit the others it shows that I booked marked them cc @calvinpete

2019-03-04 10:43 UTC, armstrongsouljah commented
Okay @calvinpete

On Mon, 4 Mar 2019 at 13:42, Muhwezi Deo <notifications@github.com> wrote:

> Please @armstrongsouljah <https://github.com/armstrongsouljah> check a
> bug u have when I bookmark an article and visit the others it shows that I
> booked marked them cc @calvinpete <https://github.com/calvinpete>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andela/Ah-frontend-xmen/pull/32#issuecomment-469205903>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARbwln8zcg7LTyTCluyWIKXDtRt0zBFjks5vTPiagaJpZM4bW7wX>
> .
>

2019-03-04 10:44 UTC, calvinpete requested changes
@armstrongsouljah It seems after bookmarking one article, the bookmark icon for other articles also changes to the bookmarked status color

2019-03-05 14:56 UTC, malfahad commented on tests/ArticleReadView.test.js
> +import { toast } from 'react-toastify';
@armstrongsouljah  please deal with the hound violations

2019-03-05 14:57 UTC, malfahad commented
@armstrongsouljah please deal with the hound violations

2019-03-05 15:21 UTC, malfahad submitted a review, later dismissed
LGTM

2019-03-05 17:04 UTC, MuhweziDeo submitted a review, later dismissed
LGTM

2019-03-05 17:05 UTC, calvinpete submitted a review, later dismissed

2019-03-05 17:25 UTC, RrNn commented on src/reducers/__tests__/bookmarkListReducer.test.js
> +    // Array.prototype.filter =  jest.fn();
Remove commented code.

2019-03-05 17:25 UTC, RrNn commented on src/reducers/__tests__/bookmarkListReducer.test.js
> +    // Array.prototype.filter =  jest.fn();
Plus this

2019-03-05 17:25 UTC, RrNn commented on src/reducers/__tests__/bookmarkListReducer.test.js
> +    // Array.prototype.filter =  jest.fn();
Plus this

2019-03-05 17:25 UTC, RrNn commented on src/reducers/__tests__/bookmarkListReducer.test.js
> +    // Array.prototype.filter =  jest.fn();
Plus this

2019-03-05 17:50 UTC, kdaglas submitted a review, later dismissed
i have tested it and the bug was fixed... LGTM

2019-03-05 19:29 UTC, calvinpete approved these changes
LGTM

2019-03-05 19:30 UTC, RrNn commented
I'll go ahead and merge in this, but we shall need to fix our tests and remove the errors.

2019-03-05 19:30 UTC, merged

2019-03-05 19:31 UTC, armstrongsouljah commented
Okay.

On Tue, 5 Mar 2019 at 22:30, Nabaasa Richard <notifications@github.com>
wrote:

> I'll go ahead and merge in this, but we shall need to fix our tests and
> remove the errors.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andela/Ah-frontend-xmen/pull/32#issuecomment-469825717>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARbwlhN7EqsaPT7pfQ7LYsTVWDUWkfLHks5vTsXcgaJpZM4bW7wX>
> .
>

2019-03-05 19:46 UTC, RrNn commented
We also have an unclear test which has an uncalled mock function. Run the current develop tets to see it.

2019-03-05 19:47 UTC, armstrongsouljah commented
We'll look into those in the morning.

On Tue, 5 Mar 2019 at 22:46, Nabaasa Richard <notifications@github.com>
wrote:

> We also have an unclear test which has an uncalled mock function. Run the
> current develop tets to see it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andela/Ah-frontend-xmen/pull/32#issuecomment-469831301>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARbwlsE6b9s_TCHu4FFcv72CwIzhMEPaks5vTsmQgaJpZM4bW7wX>
> .
>

2019-03-05 21:56 UTC, kdaglas commented
I actually saw that uncalled mock function and I also showed it to @malfahad, we will look at it today